<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseCommunityCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('community_category');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('name', 'string', 64, array('type' => 'string', 'default' => '', 'notnull' => true, 'length' => '64'));
        $this->hasColumn('is_allow_member_community', 'boolean', null, array('type' => 'boolean', 'default' => true, 'notnull' => true));
        $this->hasColumn('tree_key', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('sort_order', 'integer', 4, array('type' => 'integer', 'length' => '4'));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        $this->hasMany('Community', array('local' => 'id',
                                          'foreign' => 'community_category_id'));

        $nestedset0 = new Doctrine_Template_NestedSet(array('hasManyRoots' => true, 'rootColumnName' => 'tree_key'));
        $this->actAs($nestedset0);
    }
}