<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseNavigation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('navigation');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('caption', 'string', 2147483647, array('type' => 'string', 'notnull' => true, 'length' => '2147483647'));
        $this->hasColumn('type', 'string', 64, array('type' => 'string', 'default' => '', 'notnull' => true, 'length' => '64'));
        $this->hasColumn('uri', 'string', 2147483647, array('type' => 'string', 'notnull' => true, 'length' => '2147483647'));
        $this->hasColumn('sort_order', 'integer', 4, array('type' => 'integer', 'length' => '4'));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        $i18n0 = new Doctrine_Template_I18n(array('fields' => array(0 => 'caption'), 'length' => '5'));
        $this->actAs($i18n0);
    }
}