<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseAdminUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('admin_user');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('username', 'string', 64, array('type' => 'string', 'default' => '', 'notnull' => true, 'length' => '64'));
        $this->hasColumn('password', 'string', 40, array('type' => 'string', 'default' => '', 'notnull' => true, 'length' => '40'));

        $this->option('charset', 'utf8');
    }

}