<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profile');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('name', 'string', 64, array('type' => 'string', 'default' => '', 'notnull' => true, 'length' => '64'));
        $this->hasColumn('is_required', 'boolean', null, array('type' => 'boolean', 'default' => false, 'notnull' => true));
        $this->hasColumn('is_unique', 'boolean', null, array('type' => 'boolean', 'default' => false, 'notnull' => true));
        $this->hasColumn('is_edit_public_flag', 'boolean', null, array('type' => 'boolean', 'default' => false, 'notnull' => true));
        $this->hasColumn('default_public_flag', 'integer', 1, array('type' => 'integer', 'default' => '1', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('form_type', 'string', 32, array('type' => 'string', 'default' => '', 'notnull' => true, 'length' => '32'));
        $this->hasColumn('value_type', 'string', 32, array('type' => 'string', 'default' => '', 'notnull' => true, 'length' => '32'));
        $this->hasColumn('is_disp_regist', 'boolean', null, array('type' => 'boolean', 'default' => false, 'notnull' => true));
        $this->hasColumn('is_disp_config', 'boolean', null, array('type' => 'boolean', 'default' => false, 'notnull' => true));
        $this->hasColumn('is_disp_search', 'boolean', null, array('type' => 'boolean', 'default' => false, 'notnull' => true));
        $this->hasColumn('value_regexp', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
        $this->hasColumn('value_min', 'string', 32, array('type' => 'string', 'length' => '32'));
        $this->hasColumn('value_max', 'string', 32, array('type' => 'string', 'length' => '32'));
        $this->hasColumn('sort_order', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('caption', 'string', 2147483647, array('type' => 'string', 'notnull' => true, 'length' => '2147483647'));
        $this->hasColumn('info', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        $this->hasMany('MemberProfile', array('local' => 'id',
                                              'foreign' => 'profile_id'));

        $this->hasMany('ProfileOption', array('local' => 'id',
                                              'foreign' => 'profile_id'));

        $i18n0 = new Doctrine_Template_I18n(array('fields' => array(0 => 'caption', 1 => 'info'), 'length' => '5'));
        $this->actAs($i18n0);
    }
}