<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseMember extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('member');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('name', 'string', 64, array('type' => 'string', 'default' => '', 'notnull' => true, 'length' => '64'));
        $this->hasColumn('invite_member_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        $this->hasOne('Member', array('local' => 'invite_member_id',
                                      'foreign' => 'id'));

        $this->hasMany('CommunityMember', array('local' => 'id',
                                                'foreign' => 'member_id'));

        $this->hasMany('MemberRelationship', array('local' => 'id',
                                                   'foreign' => 'member_id_to'));

        $this->hasMany('MemberConfig', array('local' => 'id',
                                             'foreign' => 'member_id'));

        $this->hasMany('MemberImage', array('local' => 'id',
                                            'foreign' => 'member_id'));

        $this->hasMany('MemberProfile', array('local' => 'id',
                                              'foreign' => 'member_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $opactivatebehavior0 = new opActivateBehavior();
        $this->actAs($timestampable0);
        $this->actAs($opactivatebehavior0);
    }
}