<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseMemberRelationship extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('member_relationship');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('member_id_to', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
        $this->hasColumn('member_id_from', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
        $this->hasColumn('is_friend', 'boolean', null, array('type' => 'boolean'));
        $this->hasColumn('is_friend_pre', 'boolean', null, array('type' => 'boolean'));
        $this->hasColumn('is_access_block', 'boolean', null, array('type' => 'boolean'));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        $this->hasOne('Member', array('local' => 'member_id_to',
                                      'foreign' => 'id'));

        $this->hasOne('Member as Member_2', array('local' => 'member_id_from',
                                                  'foreign' => 'id'));
    }
}