<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseGadget extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gadget');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('type', 'string', 64, array('type' => 'string', 'default' => '', 'notnull' => true, 'length' => '64'));
        $this->hasColumn('name', 'string', 64, array('type' => 'string', 'default' => '', 'notnull' => true, 'length' => '64'));
        $this->hasColumn('sort_order', 'integer', 4, array('type' => 'integer', 'length' => '4'));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        $this->hasMany('GadgetConfig', array('local' => 'id',
                                             'foreign' => 'gadget_id'));
    }
}