<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseBlacklist extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('blacklist');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('uid', 'string', 32, array('type' => 'string', 'default' => '', 'notnull' => true, 'length' => '32'));
        $this->hasColumn('memo', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));

        $this->option('charset', 'utf8');
    }

}