<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseFileBin extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('file_bin');
        $this->hasColumn('file_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
        $this->hasColumn('bin', 'blob', 2147483647, array('type' => 'blob', 'length' => '2147483647'));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        $this->hasMany('File', array('local' => 'file_id',
                                     'foreign' => 'id'));
    }
}