<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseCommunity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('community');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('name', 'string', 64, array('type' => 'string', 'default' => '', 'notnull' => true, 'length' => '64'));
        $this->hasColumn('file_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('community_category_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        $this->hasOne('File', array('local' => 'file_id',
                                    'foreign' => 'id'));

        $this->hasOne('CommunityCategory', array('local' => 'community_category_id',
                                                 'foreign' => 'id'));

        $this->hasMany('CommunityMember', array('local' => 'id',
                                                'foreign' => 'community_id'));

        $this->hasMany('CommunityConfig', array('local' => 'id',
                                                'foreign' => 'community_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}