<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseMemberImage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('member_image');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('member_id', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
        $this->hasColumn('file_id', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
        $this->hasColumn('is_primary', 'boolean', null, array('type' => 'boolean'));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        $this->hasOne('Member', array('local' => 'member_id',
                                      'foreign' => 'id'));

        $this->hasOne('File', array('local' => 'file_id',
                                    'foreign' => 'id'));
    }
}