<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseMemberProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('member_profile');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('member_id', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
        $this->hasColumn('profile_id', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
        $this->hasColumn('profile_option_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('value', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
        $this->hasColumn('public_flag', 'integer', 1, array('type' => 'integer', 'length' => '1'));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        $this->hasOne('Member', array('local' => 'member_id',
                                      'foreign' => 'id'));

        $this->hasOne('Profile', array('local' => 'profile_id',
                                       'foreign' => 'id'));

        $this->hasOne('ProfileOption', array('local' => 'profile_option_id',
                                             'foreign' => 'id'));

        $nestedset0 = new Doctrine_Template_NestedSet(array('hasManyRoots' => true, 'rootColumnName' => 'tree_key'));
        $this->actAs($nestedset0);
    }
}