<?php

/**
 * CommunityMemberPosition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    OpenPNE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
class CommunityMemberPosition extends BaseCommunityMemberPosition
{
}
