
function op_mce_insert_tagname(id,tagname,opt,start,end)
{opt=opt||"";var elm=document.getElementById(id);var selection=new Selection(elm);var pos=selection.create();elm.focus();start=(start==null||start==undefined)?pos.start:start;end=(end==null||end==undefined)?pos.end:end;var replace="<"+tagname+opt+">"+elm.value.substring(start,end)+"</"+tagname+">";var head=elm.value.substring(0,start);var tail=elm.value.substring(end,elm.value.length);elm.value=head+replace+tail;}
function op_mce_show_color_table(id,tagname)
{var table=document.getElementById(id+"_color_table");var button=document.getElementById(id+"_button_op_color");var button_container=document.getElementById(id+"_buttonmenu");function close_color_table(e)
{if(e&&Element.hasClassName(e.element(),'disabledHideColorTable')){return;}
table.hide();Event.stopObserving(document,'mousedown',close_color_table);}
if(table){if(!table.visible()){table.style.display='block';Event.observe(document,'mousedown',close_color_table);}
return;}
Event.observe(document,'mousedown',close_color_table);var color=null;var settings={colors:["000000","993300","333300","003300","003366","000080","333399","333333","800000","FF6600","808000","008000","008080","0000FF","666699","808080","FF0000","FF9900","99CC00","339966","33CCCC","3366FF","800080","999999","FF00FF","FFCC00","FFFF00","00FF00","00FFFF","00CCFF","993366","C0C0C0","FF99CC","FFCC99","FFFF99","CCFFCC","CCFFFF","99CCFF","CC99FF","FFFFFF"],grid_width:8,default_color:"#888888"};var tbody=document.createElement("tbody");Element.addClassName(tbody,'disabledHideColorTable');var tr;for(var i=0;i<settings.colors.length;i++){var code="#"+settings.colors[i];if(i===0||i%settings.grid_width===0){tr=document.createElement("tr");Element.addClassName(tr,'disabledHideColorTable');tbody.appendChild(tr);}
var td=document.createElement("td");td.style.border="0 none";td.style.width="12px";td.style.padding="2px";td.style.margin="0";Element.addClassName(td,'disabledHideColorTable');var a=document.createElement("a");a.setAttribute("href","#");a.colorCode=code;a.style.width="9px";a.style.height="9px";a.style.display="block";a.style.overflow="hidden";a.style.border="1px solid #808080";a.style.backgroundColor="#"+settings.colors[i];Element.addClassName(a,'disabledHideColorTable');a.onmousedown=function(){op_mce_insert_tagname(id,tagname,' color="'+this.colorCode+'"');close_color_table();return false;};var span=document.createElement("span");span.style.display="none";span.appendChild(document.createTextNode(code));a.appendChild(span);td.appendChild(a);tr.appendChild(td);}
table=document.createElement("table");table.id=id+"_color_table";table.style.width="auto";table.style.position="absolute";table.style.zIndex=150;table.style.border="1px solid gray";table.style.backgroundColor="#fff";table.appendChild(tbody);Element.addClassName(table,'disabledHideColorTable');button_container.appendChild(table);var buttonPosition=Position.cumulativeOffset(button);table.style.left=buttonPosition[0]+"px";table.style.top=buttonPosition[1]+button.offsetHeight+"px";}
function op_insert_str_to_selection(elm,str,start,end)
{var selection=new Selection(elm);var pos=selection.create();elm.focus();start=(start==null||start==undefined)?pos.start:start;end=(end==null||end==undefined)?pos.end:end;var head=elm.value.substring(0,pos.start);var tail=elm.value.substring(pos.end,elm.value.length);elm.value=head+str+tail;}