<?php

/**
 * IntroFriendUnreadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IntroFriendUnreadTable extends PluginIntroFriendUnreadTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object IntroFriendUnreadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IntroFriendUnread');
    }
}