<?php

/**
 * IntroFriendTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IntroFriendTable extends PluginIntroFriendTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object IntroFriendTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IntroFriend');
    }
}