<?php
include(dirname(__FILE__).'/../../bootstrap/functional.php');

$browser = new opTestFunctional(new opBrowser(), new lime_test(null, new lime_output_color()));
$browser
  ->info('Login')
  ->get('/')
  ->click('ログイン', array('admin_user' => array(
    'username' => 'admin',
    'password' => 'password',
  )))

  ->info('/plugin/list/type/application - CSRF')
  ->post('/plugin/list/type/application', array())
  ->followRedirect()
  ->checkCSRF()

  ->info('/plugin/list/type/auth - CSRF')
  ->post('/plugin/list/type/auth', array())
  ->followRedirect()
  ->checkCSRF()

  ->info('/plugin/list/type/skin - CSRF')
  ->post('/plugin/list/type/skin', array())
  ->followRedirect()
  ->checkCSRF()

  ->info('/plugin/install - CSRF')
  ->post('/plugin/install', array())
  ->checkCSRF()

  ->info('/plugin/install - stable plugin')
  ->get('/plugin/list')
  ->setField('plugin_install[name]', 'opSkinBasicGreenPlugin')
  ->click('インストール実行')
  ->with('request')->begin()
    ->isParameter('module', 'plugin')
    ->isParameter('action', 'install')
  ->end()
  ->with('response')->begin()
    ->isStatusCode(302)
  ->end()
  ->followRedirect()
  ->with('request')->begin()
    ->isParameter('module', 'plugin')
    ->isParameter('action', 'list')
  ->end()
  ->with('response')->begin()
    ->isStatusCode(200)
    ->checkElement('.flash', '/プラグインの追加が完了しました。/')
  ->end()

  ->info('/plugin/install - plugin name empty')
  ->get('/plugin/list')
  ->click('インストール実行')
  ->with('request')->begin()
    ->isParameter('module', 'plugin')
    ->isParameter('action', 'install')
  ->end()
  ->with('response')->begin()
    ->isStatusCode(200)
    ->checkElement('.error_list li', '/必須項目です/')
  ->end()

  ->info('/plugin/install - instable plugin')
  ->get('/plugin/list')
  ->setField('plugin_install[name]', 'opPortalPlugin')
  ->click('インストール実行')
  ->with('request')->begin()
    ->isParameter('module', 'plugin')
    ->isParameter('action', 'install')
  ->end()
  ->with('response')->begin()
    ->isStatusCode(200)
    ->checkElement('.error_list li', '/安定版が存在しません。非安定版をインストールする場合は、バージョン番号を指定してください。/')
  ->end()
  
  ->info('/plugin/install - instable plugin (with version specified)')
  ->setField('plugin_install[version]', '0.9.1.1')
  ->click('インストール実行')
  ->with('request')->begin()
    ->isParameter('module', 'plugin')
    ->isParameter('action', 'install')
  ->end()
  ->with('response')->begin()
    ->isStatusCode(302)
  ->end()
  ->followRedirect()
  ->with('request')->begin()
    ->isParameter('module', 'plugin')
    ->isParameter('action', 'list')
  ->end()
  ->with('response')->begin()
    ->isStatusCode(200)
    ->checkElement('.flash', '/プラグインの追加が完了しました。/')
  ->end()


  ->info('/plugin/install - non-existant plugin')
  ->get('/plugin/list')
  ->setField('plugin_install[name]', 'opFooBarPlugin')
  ->click('インストール実行')
  ->with('request')->begin()
    ->isParameter('module', 'plugin')
    ->isParameter('action', 'install')
  ->end()
  ->with('response')->begin()
    ->isStatusCode(200)
    ->checkElement('.error_list li', '/プラグインが見つかりません。/')
  ->end()

  ->info('/plugin/uninstall - CSRF')
  ->post('/plugin/uninstall', array('name' => 'opPortalPlugin'))
  ->checkCSRF()

  ->info('/plugin/uninstall - plugin plugin')
  ->get('/plugin/uninstall?name=opSkinBasicGreenPlugin')
  ->with('request')->begin()
    ->isParameter('module', 'plugin')
    ->isParameter('action', 'uninstall')
  ->end()
  ->with('response')->begin()
    ->isStatusCode(200)
  ->end()
  ->click('アンインストール実行')
  ->with('request')->begin()
    ->isParameter('module', 'plugin')
    ->isParameter('action', 'uninstall')
  ->end()
  ->with('response')->begin()
    ->isStatusCode(302)
  ->end()
  ->followRedirect()
  ->with('request')->begin()
    ->isParameter('module', 'plugin')
    ->isParameter('action', 'list')
  ->end()
  ->with('response')->begin()
    ->isStatusCode(200)
    ->checkElement('.flash', '/プラグインの削除が完了しました。/')
  ->end()
;
